# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171203_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
